名称：百度_speed@Sunert3
在：
    workflow_dispatch：
    时间表：
- cron：“*/20 0-23/1 * * *”
    观看：
      类型：[开始]
工作：
  构建：
    运行：ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env：
        BAIDU_COOKIE：${{ secrets.BAIDU_COOKIE }}
        TZ：亚洲/上海
    步骤：
- 名称：结账
        用途：actions/checkout@v2
-名称：使用Node.js 12.x
        用途：actions/setup-node@v1
        与：
          节点版本：12.x
-名称：npm安装
        运行：|
npm安装
-名称：'运行[百度极速版]'
        if：env.BAIDU_COOKIE
        运行：|
节点任务/baidu_speed.js
        env：
          BAIDU_CASH：${{ secrets.BAIDU_CASH }}
          BAIDU_COOKIE：${{ secrets.BAIDU_COOKIE }}
          PUSH_KEY：${ secrets.PUSH_KEY }}
