name: jjj

on:
  workflow_dispatch:
  schedule:
     - cron: '0/15 4,7,12,20,23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        LOADRESOURCEBODY: ${{ secrets.LOADRESOURCEBODY }}
        LOADRESOURCEKEY: ${{ secrets.LOADRESOURCEKEY }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【jjj】'
        if: env.LOADRESOURCEBODY
        run: |
          node Task/jjj.js
        env:
          LOADRESOURCEBODY: ${{ secrets.LOADRESOURCEBODY }}
          LOADRESOURCEKEY: ${{ secrets.LOADRESOURCEKEY }}
          SPLOADRESOURCEBODY: ${{ secrets.SPLOADRESOURCEBODY }}
          SPLOADRESOURCEKEY: ${{ secrets.SPLOADRESOURCEKEY }}
          WITHDRAWBODY: ${{ secrets.WITHDRAWBODY }}
          BUBBLEBODY: ${{ secrets.BUBBLEBODY }}
          RECEIVEBODY: ${{ secrets.RECEIVEBODY }}
          SIGNINACTIONBODY: ${{ secrets.SIGNINACTIONBODY }}
          READLOTTERYBODY: ${{ secrets.READLOTTERYBODY }}
          VIDEOLOTTERYBODY: ${{ secrets.VIDEOLOTTERYBODY }}
          LUCKYLOTTERYBODY: ${{ secrets.LUCKYLOTTERYBODY }}
          LUCKYREDURL: ${{ secrets.LUCKYREDURL }}
          LUCKYREDBODY: ${{ secrets.LUCKYREDBODY }}
          SHAREBODY: ${{ secrets.SHAREBODY }}
          BOOKTASKURL: ${{ secrets.BOOKTASKURL }}
          BOOKTASKBODY: ${{ secrets.BOOKTASKBODY }}
          SPSIGNINACTIONBODY: ${{ secrets.SPSIGNINACTIONBODY }}
          SPREADCOINURL: ${{ secrets.SPREADCOINURL }}
          SPREADCOINBODY: ${{ secrets.SPREADCOINBODY }}
          SP1VIDEOCOINBODY: ${{ secrets.SP1VIDEOCOINBODY }}
          SP2VIDEOCOINBODY: ${{ secrets.SP2VIDEOCOINBODY }}
          SPSHAREBODY: ${{ secrets.SPSHAREBODY }}
          LOTTERYINFOURL: ${{ secrets.LOTTERYINFOURL }}
          VIDEOINFOURL: ${{ secrets.VIDEOINFOURL }}
          SPVIDEOINFOUR: ${{ secrets.SPVIDEOINFOUR }}
