# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# push:
#   branches: 
#   - master 

name: jjsq

on:
  workflow_dispatch:
  schedule:
     - cron: '0/20 0-23 * * *'
  watch:
     types: started
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【jjsq】'
        run: |
          node Task/shuqi.js
        env:
          LOADRESOURCEBODY: ${{ secrets.LOADRESOURCEBODY }}
          LOADRESOURCEKEY: ${{ secrets.LOADRESOURCEKEY }}
          SPLOADRESOURCEBODY: ${{ secrets.SPLOADRESOURCEBODY }}
          SPLOADRESOURCEKEY: ${{ secrets.SPLOADRESOURCEKEY }}
      WITHDRAWBODY: ${{ secrets.WITHDRAWBODY }}
      BUBBLEBODY: ${{ secrets.BUBBLEBODY }}
      RECEIVEBODY: ${{ secrets.RECEIVEBODY }}
      SIGNINACTIONBODY: ${{ secrets.SIGNINACTIONBODY }}
      READLOTTERYBODY: ${{ secrets.READLOTTERYBODY }}
      VIDEOLOTTERYBODY: ${{ secrets.VIDEOLOTTERYBODY }}
      LUCKYLOTTERYBODY: ${{ secrets.LUCKYLOTTERYBODY }}
      LUCKYREDURL: ${{ secrets.LUCKYREDURL }}
      LUCKYREDBODY: ${{ secrets.LUCKYREDBODY }}
      SHAREBODY: ${{ secrets.SHAREBODY }}
      BOOKTASKURL: ${{ secrets.BOOKTASKURL }}
      BOOKTASKBODY: ${{ secrets.BOOKTASKBODY }}
      SPSIGNINACTIONBODY: ${{ secrets.SPSIGNINACTIONBODY }}
      SPREADCOINURL: ${{ secrets.SPREADCOINURL }}
      SPREADCOINBODY: ${{ secrets.SPREADCOINBODY }}
      SP1VIDEOCOINBODY: ${{ secrets.SP1VIDEOCOINBODY }}
      SP2VIDEOCOINBODY: ${{ secrets.SP2VIDEOCOINBODY }}
      SPSHAREBODY: ${{ secrets.SPSHAREBODY }}
      LOTTERYINFOURL: ${{ secrets.LOTTERYINFOURL }}
      VIDEOINFOURL: ${{ secrets.VIDEOINFOURL }}
      SPVIDEOINFOUR: ${{ secrets.SPVIDEOINFOUR }}
