name: 中青邀请阅读

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '6 0,7,8,10,13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/niubi-66/B.git ~/B
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/B
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行 【中青邀请阅读】'
        run: |
          cd ~/B
          node Task/zqfx.js
